image: Visual Studio 2017

environment:
  VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  matrix:
    - TARGET_PLATFORM: windows-64
      ARCH: amd64
      PYTHON: C:\Python37-x64
    - TARGET_PLATFORM: windows-32
      ARCH: amd64_x86
      PYTHON: C:\Python37

install:
  - git submodule update --init --recursive
  - set "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # - set "PATH=C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin;%PATH%"
  - git rev-parse HEAD
  - call "%VS%" %ARCH%
  - python --version
  - cl.exe

before_build:
  - pip install -r requirements.txt
  - ps: if($env:DEBUG -eq "true") { iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')) }

build_script:
  # Un-comment if you're in deep troubles...
  # - set SCONS_MSCOMMON_DEBUG=-
  - ps: if($env:APPVEYOR_REPO_TAG -eq "false") { $env:SAMPLE_ARG = "sample=true" }
  - scons platform=%TARGET_PLATFORM% release_suffix=%APPVEYOR_REPO_TAG_NAME% %SAMPLE_ARG% release

after_build:
  - ls -l build
  - du -sh build/
  - ls -l build/pythonscript-*
  - ls -l godot-python-*.zip

# test:
#   - scons platform=%TARGET_PLATFORM% release_suffix=%APPVEYOR_REPO_TAG_NAME% test

# on_failure:
#   - 7z -tzip a CPythonBuild.zip platforms\windows-64\cpython
#   - appveyor PushArtifact CPythonBuild.zip
#   - 7z -tzip a GodotPythonBuild.zip build
#   - appveyor PushArtifact GodotPythonBuild.zip

artifacts:
  - path: godot-python-*.zip
    name: GodotPythonRelease

deploy:
  provider: GitHub
  auth_token:
    secure: +E+qs6rzwl8SqOPcerXoBpVYG4HUzh3Juyj02aYrHvnF6YqX2wbP1dEDjY5SHBD5
  artifact: GodotPythonRelease
  on:
    appveyor_repo_tag: true
